# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnorm_rcpp <- function(n, mu, sigma) {
    .Call(`_Bio2005_mvrnorm_rcpp`, n, mu, sigma)
}

#' @title A Rcpp version of Wnm
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]Wnm and [2]p-value
#' @export
#'
#' @examples Wnm_rcpp(DGP(n = 5, m = 4, rho = 0))
Wnm_rcpp <- function(X) {
    .Call(`_Bio2005_Wnm_rcpp`, X)
}

#' @title A Rcpp version of Tnm
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]Tnm and [2]p-value
#' @export
#'
#' @examples Tnm_rcpp(DGP(n = 5, m = 4, rho = 0))
Tnm_rcpp <- function(X) {
    .Call(`_Bio2005_Tnm_rcpp`, X)
}

