// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// beta_tau_mt
NumericMatrix beta_tau_mt(int n2, int m, int d, float delta_tau, NumericMatrix beta0_tau_hat, NumericVector tau_seq, NumericMatrix u_mt, NumericMatrix int_u_mt, NumericMatrix Xmis_mt, NumericMatrix ymis_mt);
RcppExport SEXP _qrMNAR_beta_tau_mt(SEXP n2SEXP, SEXP mSEXP, SEXP dSEXP, SEXP delta_tauSEXP, SEXP beta0_tau_hatSEXP, SEXP tau_seqSEXP, SEXP u_mtSEXP, SEXP int_u_mtSEXP, SEXP Xmis_mtSEXP, SEXP ymis_mtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    Rcpp::traits::input_parameter< float >::type delta_tau(delta_tauSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta0_tau_hat(beta0_tau_hatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau_seq(tau_seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type u_mt(u_mtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type int_u_mt(int_u_mtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Xmis_mt(Xmis_mtSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type ymis_mt(ymis_mtSEXP);
    rcpp_result_gen = Rcpp::wrap(beta_tau_mt(n2, m, d, delta_tau, beta0_tau_hat, tau_seq, u_mt, int_u_mt, Xmis_mt, ymis_mt));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_qrMNAR_beta_tau_mt", (DL_FUNC) &_qrMNAR_beta_tau_mt, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_qrMNAR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
