# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvrnorm_rcpp <- function(n, mu, sigma) {
    .Call(`_CSTM2017_mvrnorm_rcpp`, n, mu, sigma)
}

#' @title A Rcpp version of Tnm
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]Tnm and [2]p-value
#' @export
#'
#' @examples Tnm_rcpp(DGP(N = 4, m = 4, case = 1))
Tnm_rcpp <- function(X) {
    .Call(`_CSTM2017_Tnm_rcpp`, X)
}

#' @title A Rcpp version of Snm
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]Snm and [2]p-value
#' @export
#'
#' @examples Snm_rcpp(DGP(N = 4, m = 4, case = 1))
Snm_rcpp <- function(X) {
    .Call(`_CSTM2017_Snm_rcpp`, X)
}

#' @title A Rcpp version of T3
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]T3 and [2]p-value
#' @export
#'
#' @examples T3_rcpp(DGP(N = 4, m = 4, case = 1))
T3_rcpp <- function(X) {
    .Call(`_CSTM2017_T3_rcpp`, X)
}

#' @title A Rcpp version of T_rho
#'
#' @param X a n*m matrix
#' @return     a vector contain [1]T_rho and [2]p-value
#' @export
#'
#' @examples Trho_rcpp(DGP(N = 4, m = 4, case = 1))
Trho_rcpp <- function(X) {
    .Call(`_CSTM2017_Trho_rcpp`, X)
}

