# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate Tks.rand (rcpp version)
#'
#' @param V cbind(X.hat, Z) a n*(p+q) matrix
#' @param theta
#' @param e e.hat
#'
#' @return Tks test statistics(3.1)
#' @export
#'
#' @examples Tks_rand_rcpp(V, theta.normal, e.hat)
Tks_rand_rcpp <- function(V, theta, e) {
    .Call(`_Sinica2022_Tks_rand_rcpp`, V, theta, e)
}

