# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Tnsc_rcpp <- function(x, y, ytilde, c) {
    .Call(`_Bierens2012_Tnsc_rcpp`, x, y, ytilde, c)
}

