# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

outerminus <- function(X) {
    .Call(`_rRAT_outerminus`, X)
}

bubbleSortX <- function(x, y) {
    .Call(`_rRAT_bubbleSortX`, x, y)
}

mtau <- function(x, y) {
    .Call(`_rRAT_mtau`, x, y)
}

taucpp <- function(X) {
    .Call(`_rRAT_taucpp`, X)
}

allmain <- function(X) {
    .Call(`_rRAT_allmain`, X)
}

