# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

beta_tau_mt <- function(n2, m, d, delta_tau, beta0_tau_hat, tau_seq, u_mt, int_u_mt, Xmis_mt, ymis_mt) {
    .Call(`_qrMNAR_beta_tau_mt`, n2, m, d, delta_tau, beta0_tau_hat, tau_seq, u_mt, int_u_mt, Xmis_mt, ymis_mt)
}

