# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

slm_rcpp <- function(x, y) {
    .Call(`_ECCFIC2024_slm_rcpp`, x, y)
}

ptest_slm_rcpp <- function(x, y, B) {
    .Call(`_ECCFIC2024_ptest_slm_rcpp`, x, y, B)
}

kem_rcpp <- function(x, y) {
    .Call(`_ECCFIC2024_kem_rcpp`, x, y)
}

ptest_kem_rcpp <- function(x, y, B) {
    .Call(`_ECCFIC2024_ptest_kem_rcpp`, x, y, B)
}

